"""
agents/pull_request_agent.py

Milestone 10

Responsible for:

- Creating Pull Requests
- Storing PR information in AgentState
"""

from tools.github_pr_tool import GitHubPRTool


class PullRequestAgent:

    def __init__(self):

        self.github = GitHubPRTool()

    # ---------------------------------------------------------
    # Create Pull Request
    # ---------------------------------------------------------

    def create_pull_request(
        self,
        state,
    ):

        print()

        print("=" * 70)
        print("PULL REQUEST AGENT")
        print("=" * 70)

        if not getattr(
            state,
            "delivery_completed",
            False,
        ):

            print(
                "Repository has not been pushed."
            )

            print(
                "Skipping Pull Request creation."
            )

            return state

        title = (
            f"{state.issue_key}: {state.summary}"
        )

        body = f"""
## Jira Issue

{state.issue_key}

## Summary

{state.summary}

## Description

Automatically generated by the Autonomous Software Engineering Agent.

## Changes

- AI Generated
- Patch Validated
- Tests Passed
- Ready for Review
"""

        pr = self.github.create_pull_request(

            repository_url=state.repository,

            title=title,

            body=body,

            head_branch=state.feature_branch,

            base_branch=state.branch,

        )

        state.pull_request_number = pr.number

        state.pull_request_url = pr.html_url

        print()

        print(
            f"Pull Request #{pr.number} created."
        )

        print(
            pr.html_url
        )

        print("=" * 70)

        return state

    # ---------------------------------------------------------
    # Add Comment
    # ---------------------------------------------------------

    def add_comment(
        self,
        state,
        comment,
    ):

        if not getattr(
            state,
            "pull_request_number",
            None,
        ):

            return

        self.github.add_comment(

            repository_url=state.repository,

            pr_number=state.pull_request_number,

            comment=comment,

        )

    # ---------------------------------------------------------
    # Summary
    # ---------------------------------------------------------

    def print_summary(
        self,
        state,
    ):

        print()

        print("=" * 70)
        print("PULL REQUEST SUMMARY")
        print("=" * 70)

        print(
            "PR Number :",
            getattr(
                state,
                "pull_request_number",
                None,
            ),
        )

        print(
            "PR URL    :",
            getattr(
                state,
                "pull_request_url",
                None,
            ),
        )

        print("=" * 70)