"""
tools/code_patch.py

Purpose
-------
Represent code changes generated by the Coding Agent.

This component does NOT modify files.

Instead, it converts an LLM response into a structured set of
patch operations that can later be validated, reviewed and applied.

Future Milestones
-----------------
- Unified Diff support
- Git Patch support
- AST-aware patching
- Three-way merge
"""

from dataclasses import dataclass, field


# ============================================================
# Patch Operation
# ============================================================

@dataclass
class PatchOperation:
    """
    Represents one file modification.
    """

    file_path: str

    operation: str

    old_content: str = ""

    new_content: str = ""


# ============================================================
# Patch
# ============================================================

@dataclass
class CodePatch:
    """
    Represents a collection of repository changes.
    """

    operations: list[PatchOperation] = field(
        default_factory=list
    )

    # ---------------------------------------------------------
    # Add Operation
    # ---------------------------------------------------------

    def add_operation(
        self,
        operation: PatchOperation,
    ):
        """
        Add one patch operation.
        """

        self.operations.append(operation)

    # ---------------------------------------------------------
    # Statistics
    # ---------------------------------------------------------

    def total_operations(self):
        """
        Return number of file changes.
        """

        return len(self.operations)

    # ---------------------------------------------------------
    # Console
    # ---------------------------------------------------------

    def print_summary(self):
        """
        Display patch summary.
        """

        print()

        print("=" * 70)
        print("CODE PATCH")
        print("=" * 70)

        if not self.operations:

            print("No operations generated.")

            print("=" * 70)

            return

        for index, operation in enumerate(
            self.operations,
            start=1,
        ):

            print()

            print(f"{index}. {operation.operation}")

            print(
                f"File : {operation.file_path}"
            )

        print()

        print(
            f"Total Operations : {len(self.operations)}"
        )

        print("=" * 70)